### ISSUE TITLE
Create a Secret Provider for Vault's transit secret backend

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/tokend#57]
Vault has a [transit secret backend](https://www.vaultproject.io/docs/secrets/transit/index.html) that we need a **Secret Provider** for. See #1 for the definition of a Secret Provider.

The `TransitProvider` class has the following methods:

**constructor(secret, token)**
Create a new instance of a `TransitSecretProvider`.

The `secret.key` argument is a string used to identify the key in Vault for decrypting the ciphertext.

The `secret.ciphertext` argument is a string of the ciphertext to decrypt.

The `token` argument is a string of the token to pass to Vault's API.

**initialize()**
Returns a `Promise` that resolves with the ciphertext when decryption is complete. If decryption has already happened, this will return a resolved `Promise` immediately. If decryption hasn't happened yet, this will use Vault's [`/transit/decrypt/<name>` API](https://www.vaultproject.io/docs/secrets/transit/index.html) to decrypt the ciphertext. The `<name>` parameter comes from the `secret.key` argument provided to the constructor.

**renew()**
Returns a `Promise` that resolves with the ciphertext when decryption is complete. This always calls Vault's [`/transit/decrypt/<name>` API](https://www.vaultproject.io/docs/secrets/transit/index.html) to decrypt the ciphertext. The `<name>` parameter comes from the `secret.key` argument provided to the constructor.

**Comment by dgreene-r7** [comment]
The `constructor` for the other Providers has the `(key, token, options)` signature. Other than that, looks good!

**Comment by fmitchell-r7** [comment]
@dgreene-r7, do we want to stick with that signature (`key, token, [options]`) and have `ciphertext` be an argument to `initialize()` instead?

**Comment by dgreene-r7** [comment]
Why don't we have `options.ciphertext` be a required argument. You can use `checkNotNull` to confirm its existence (see the pattern here: https://github.com/rapid7/tokend/blob/master/lib/providers/token.js#L48-L51)

**Comment by fmitchell-r7** [comment]
Updated description based on an out of band conversation with @dgreene-r7. We settled on `constructor(key, token, parameters)` to match the signature of the other providers.

**Comment by fmitchell-r7** [comment]
I updated the description so the `TransitProvider#constructor` takes the ciphertext and key as a single `secret` Object. This will make it easier to use with the `/v1/transit` API defined in #59.
