### ISSUE TITLE
Create a /v1/transit API for Vault's transit secret backend

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/tokend#59]
Once we have a Secret Provider that uses Vault's transit secret backend to decrypt secrets (see #57), we need to set up a `/v1/transit` API.

Method: `POST`

URL: `/v1/transit/<token>/decrypt`

Body: `application/json`
```javascript
{
  "key": "<key>",
  "ciphertext": "<ciphertext>"
}
```

Returns: `200 OK`
```javascript
{
  "plaintext": "..."
}
```

The `<key>` and `<ciphertext>` parameters must be Base64 encoded as per [RFC 4648](https://tools.ietf.org/html/rfc4648).

A `TransitProvider` can be created by doing
```javascript
const key = "<key>";
const token = "<token>";
const parameters = {
  "ciphertext": "<ciphertext>"
};
new TransitProvider(key, token, parameters);
```
If the `<token>` in the URL is `default`, Tokend's internal default token should be used.

Decrypted ciphertext returned from Vault will be Base64 encoded. The API should decode the plaintext before returning it to the client.

**Comment by dgreene-r7** [comment]
The `encrypt` endpoint should be in the scope of this issue.

The service @asebastian-r7 is writing could take advantage of it and not have to connect directly to Vault at all.

**Comment by fmitchell-r7** [comment]
Per an out of band conversation with @athompson-r7 and @jmanero-r7, I was reminded that URLs have a length limit. See keeping `<key>` and `<ciphertext>` in the URL isn't the way to go here. We should POST a JSON body with those values instead.

This requires some refactoring to the way the [storage layer caches secrets](https://github.com/rapid7/tokend/blob/master/lib/storage-service.js#L90). Since we'll now need to account for a secret that's JSON.
